name: water-level-daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  run_pipelines:
    runs-on: ubuntu-latest
    environment: prod

    permissions:
      contents: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run notebooks (sequential) using configs/sensors.json
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python scripts/run_batch_job.py

      - name: show git status (debug)
        run: |
          git status --porcelain
          git check-ignore -v artifacts/predictions/*.csv || true

      - name: commit updated artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update water level predictions"
          file_pattern: |
            artifacts/predictions/*.csv
          status_options: '--untracked-files=no'
